package com.Model;
// Generated 19 oct. 2015 12:59:09 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private String numclient;
     private String nomclient;
     private Set commandes = new HashSet(0);

    public Client() {
    }

    public Client(String numclient) {
        this.numclient = numclient;
    }

	
    public Client(String numclient, String nomclient) {
        this.numclient = numclient;
        this.nomclient = nomclient;
    }
    public Client(String numclient, String nomclient, Set commandes) {
       this.numclient = numclient;
       this.nomclient = nomclient;
       this.commandes = commandes;
    }
   
    public String getNumclient() {
        return this.numclient;
    }
    
    public void setNumclient(String numclient) {
        this.numclient = numclient;
    }
    public String getNomclient() {
        return this.nomclient;
    }
    
    public void setNomclient(String nomclient) {
        this.nomclient = nomclient;
    }
    public Set getCommandes() {
        return this.commandes;
    }
    
    public void setCommandes(Set commandes) {
        this.commandes = commandes;
    }




}


