package com.Model;
// Generated 19 oct. 2015 12:59:09 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Commande generated by hbm2java
 */
public class Commande  implements java.io.Serializable {


     private Integer id;
     private Produit produit= new Produit();
     private Client client = new Client();
     private Long qtecommande;
     private Date datecommande;
     private String annee;
     private Date debut,fin;
    public Commande() {
    }
public Commande( Client client, Long qtecommande) {       
       this.client = client;
       this.qtecommande = qtecommande;      
    }
    public Commande(Produit produit, Client client, Long qtecommande, Date datecommande, String annee) {
       this.produit = produit;
       this.client = client;
       this.qtecommande = qtecommande;
       this.datecommande = datecommande;
       this.annee = annee;
    }

    public Date getDebut() {
        return debut;
    }

    public void setDebut(Date debut) {
        this.debut = debut;
    }

    public Date getFin() {
        return fin;
    }

    public void setFin(Date fin) {
        this.fin = fin;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Produit getProduit() {
        return this.produit;
    }
    
    public void setProduit(Produit produit) {
        this.produit = produit;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Long getQtecommande() {
        return this.qtecommande;
    }
    
    public void setQtecommande(Long qtecommande) {
        this.qtecommande = qtecommande;
    }
    public Date getDatecommande() {
        return this.datecommande;
    }
    
    public void setDatecommande(Date datecommande) {
        this.datecommande = datecommande;
    }
    public String getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(String annee) {
        this.annee = annee;
    }




}


